-- grouping by listing (all info for listing)
-- grouping by category



-- OPTION 1
CREATE TABLE IF NOT EXISTS ALL_LISTING_DATA (
  LISTINGID int,
  TITLE text STATIC,
  CLAIMED BOOLEAN,
  PRICE INT,
  RATINGID INT,
  RATING INT,
  CATEGORYID INT,
  CATEGORY text,
  PRIMARY KEY (LISTINGID)
)
-- sample query: SELECT * FROM LISTING_RATINGS WHERE LISTINGID ='1';
CREATE TABLE IF NOT EXISTS LISTINGS_BY_CATEGORY (
  LISTINGID int,
  TITLE text,
  CLAIMED BOOLEAN,
  PRICE INT,
  RATINGID INT,
  RATING INT,
  CATEGORYID INT,
  CATEGORY text,
  PRIMARY KEY (LISTINGID, CATEGORY)
)