CREATE TABLE LISTING (
 LISTINGID SERIAL PRIMARY KEY,
 TITLE VARCHAR(80),
 CLAIMED INT,
 PRICE INT
);

CREATE TABLE REVIEWS (
  REVIEWID SERIAL PRIMARY KEY,
  RATING INT,
  LISTINGID INT NOT NULL,
  FOREIGN KEY (LISTINGID)
    REFERENCES LISTING (LISTINGID)
);

CREATE TABLE IF NOT EXISTS CATEGORIES (
  CATEGORYID SERIAL PRIMARY KEY,
  CATEGORY VARCHAR(40),
  LISTINGID INT NOT NULL,
  FOREIGN KEY (LISTINGID)
    REFERENCES LISTING (LISTINGID)
);
