CREATE TABLE IF NOT EXISTS LISTINGS (
 LISTINGID SERIAL PRIMARY KEY,
 TITLE VARCHAR(100),
 CLAIMED BOOLEAN,
 PRICE INT
);

CREATE TABLE IF NOT EXISTS REVIEWS (
  REVIEWID SERIAL PRIMARY KEY,
  RATING INT,
  REVIEWDATE DATE,
  LISTINGID INT NOT NULL,
  FOREIGN KEY (LISTINGID)
    REFERENCES LISTINGS (LISTINGID)
);

CREATE TABLE IF NOT EXISTS CATEGORIES (
  CATEGORYID SERIAL PRIMARY KEY,
  CATEGORY VARCHAR(80),
  LISTINGID INT NOT NULL,
  FOREIGN KEY (LISTINGID)
    REFERENCES LISTINGS (LISTINGID)
);
